<a href="https://colab.research.google.com/github/PabloBogg/Python_Machine_Learning_For_Beginners/blob/main/python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **PYTHON MACHINE LEARNING FOR BEGINNERS**
**Learning from scratch Numpy, Pandas, Matplotlib, Seaborn, Scikitlearn, and TensorFlow for MAchine Learning and Data Science**


*To get the Python codes and materials used in this book, please click the link below:*

www.aipublishing.io/book-machine-learning-python

*The order number is required.*

# **1**
# **Introduction and Environment Set Up**

**1.3.4. Using Google Colab Cloud Environment**

To make sure you are running the latest version of TensorFlow,
execute the following script in the Google Colab notebook
cell. The following script will update your TensorFlow version.

In [ ]:
pip install --upgrade tensorflow

To check if you are really running TensorFlow version > 2.0,
execute the following script.

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.18.0


# **3**
# **Python NumPy Library for Data Analysis**

In [ ]:
pip install numpy


Script 1:

In [ ]:
  import numpy as np
  nums_list=[10,12,15,16,20]
  nums_array=np.array(nums_list)
  print(nums_list)
  print(nums_array)
  type(nums_array)

[10, 12, 15, 16, 20]
[10 12 15 16 20]


numpy.ndarray

Script 2:


In [ ]:
row1=[10,12,13]
row2=[45,32,16]
row3=[45,32,16]

nums_2d=np.array([row1,row2,row3])
print(nums_2d.shape)
print(nums_2d)

(3, 3)
[[10 12 13]
 [45 32 16]
 [45 32 16]]


Script 3:


In [ ]:
nums_arr=np.arange(5,11)
print(nums_arr)

[ 5  6  7  8  9 10]


Script 4:


In [ ]:
nums_arr=np.arange(5,12,2)
print(nums_arr)

[ 5  7  9 11]


Script 5:


In [ ]:
ones_array=np.ones(6)
print(ones_array)

[1. 1. 1. 1. 1. 1.]


Scritp 6:


In [ ]:
ones_array=np.ones((6,4))
print(ones_array)
print(type(ones_array[0]))
print(type(ones_array[0][0]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>
<class 'numpy.float64'>


Script 7:


In [ ]:
zeros_array=np.zeros(6)
print(zeros_array)

[0. 0. 0. 0. 0. 0.]


Script 8:


In [ ]:
zeros_array=np.zeros((6,4))
print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Script 9:


In [ ]:
eyes_array=np.eye(5)
print(eyes_array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Script 10:


In [ ]:
uniform_random=np.random.rand(4,5)
print(uniform_random)

[[0.32175643 0.75663327 0.30528726 0.26301441 0.33828363]
 [0.58720461 0.79046828 0.05814425 0.8751265  0.40140239]
 [0.91461773 0.8656336  0.6121277  0.88416695 0.54385623]
 [0.56578047 0.22521276 0.70624111 0.13202266 0.38920951]]


Script 11:


In [ ]:
normal_random=np.random.randn(4,5)
print(normal_random)

[[ 0.74712341 -0.54637608  1.14326876  0.15145619  0.88577556]
 [-0.09681656 -0.24031422  0.0423955  -0.62558384 -1.18520116]
 [-0.15182341  0.33954775 -0.40428057 -0.36423599 -1.16146767]
 [ 1.26091801  0.21702652 -0.22563687  0.16280577 -0.97963128]]


Script 12:


In [ ]:
integer_random=np.random.randint(10,50,5)
print(integer_random)

[11 41 40 24 46]


Script 13:


In [ ]:
uniform_random=np.random.rand(4,6)
print(uniform_random)
uniform_random=uniform_random.reshape(3,8)
print(uniform_random)

[[0.06185942 0.64443503 0.8502673  0.32685166 0.08804058 0.81227685]
 [0.72443723 0.68105198 0.57161478 0.06472705 0.65957572 0.38726265]
 [0.32440893 0.36183747 0.55702871 0.7241518  0.72391913 0.0622471 ]
 [0.41774518 0.69162014 0.97006265 0.54044499 0.76329782 0.17426024]]
[[0.06185942 0.64443503 0.8502673  0.32685166 0.08804058 0.81227685
  0.72443723 0.68105198]
 [0.57161478 0.06472705 0.65957572 0.38726265 0.32440893 0.36183747
  0.55702871 0.7241518 ]
 [0.72391913 0.0622471  0.41774518 0.69162014 0.97006265 0.54044499
  0.76329782 0.17426024]]


Script 14:


In [ ]:
s=np.arange(1,11)
print(s)

[ 1  2  3  4  5  6  7  8  9 10]


Script 15.


In [ ]:
print(s[1])

2


Script 16:


In [ ]:
print(s[1:9])

[2 3 4 5 6 7 8 9]


Script 17:


In [ ]:
print(s[:5])
print(s[5:])

[1 2 3 4 5]
[ 6  7  8  9 10]


Script 18:


In [ ]:
row1=[10,12,13]
row2=[45,32,16]
row3=[54,23,61]

nums_2d=np.array([row1,row2,row3])
print(nums_2d[:2,:2])

[[10 12]
 [45 32]]


Script 21:


In [ ]:
nums=[4,9,16]
np_sqr=np.sqrt(nums)
print(np_sqr)

[2. 3. 4.]


Script 22:


In [ ]:
nums=[10,20,30,40,50]
np_log=np.log(nums)
print(np_log)

[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


Script 23:


In [ ]:
nums=[10,20,30,40,50]
n=np.exp(nums)
print(n)

[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]


Script 24:


In [ ]:
nums=[10,20,30,40,50]
np_sine=np.sin(nums)
print(np_sine)

np_cos=np.cos(nums)
print(np_cos)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]


Script 25:


In [ ]:
A=np.random.randn(4,5)
B=np.random.randn(5,4)
Z=np.dot(A,B)
print(Z)

C=np.ones((3,3))
D=np.zeros((3,3))
X=np.dot(C,D)
print(X)

[[-1.31371409 -3.64023127  1.43760787 -1.43152989]
 [-1.27240867 -6.69515463 -2.32370999  2.51329999]
 [ 3.55104323  4.9503389  -0.87373795  3.18530462]
 [-2.34094143 -3.82009224 -0.5142736   0.53394846]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Script 26:


In [ ]:
row1=[1,2,3]
row2=[4,5,6]
row3=[7,8,9]

nums_2d=np.array([row1,row2,row3])
multiply=np.multiply(nums_2d,nums_2d)
print(multiply)
print(np.dot(nums_2d,nums_2d))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Script 27:


In [ ]:
row1=[1,0,0]
row2=[0,1,0]
row3=[0,0,1]

nums_2d=np.array([row1,row2,row3])
inverse=np.linalg.inv(nums_2d)
print(inverse)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Script 28:


In [ ]:
row1=[1,2,3]
row2=[4,5,6]
row3=[7,8,9]

nums_2d=np.array([row1,row2,row3])
determinant=np.linalg.det(nums_2d)
print(determinant)

0.0


Script 29:


In [ ]:
row1=[1,2,3]
row2=[4,5,6]
row3=[7,8,9]

nums_2d=np.array([row1,row2,row3])
trace=np.trace(nums_2d)
print(trace)

15


Exercise 3.1

Question 1:
Which NumPy function is used for the element-wise multiplication of two matrices?

A. np.dot(matrix1, matrix2)

**B. np.multiply(matrix1, matrix2)**

C. np.elementwise(matrix1, matrix2)

D. None of the above



Question 2:
To generate an identity matrix of four rows and four columns, which of the following functions can be used?

A. np.identity(4,4)

B. np.id(4,4)

**C. np.eye(4,4)**

D. All of the above



Question 3:
How to create the array of numbers 4,7,10,13,16 with NumPy:

A. np.arange(3, 16, 3)

B. np.arange(4, 16, 3)

C. np.arange(4, 15,3)

**D. None of the above**



Exercise 3.2

Create a random NumPy array of five rows and four columns. Using array indexing and slicing, display the items from row three to end and column two to end.

In [ ]:
a=np.random.rand(5,4)
print(a)
print(a[2:,1:])

[[0.44864613 0.13940789 0.97045414 0.29399015]
 [0.55284755 0.00490626 0.25550572 0.13366116]
 [0.21514879 0.12200679 0.36650781 0.8296915 ]
 [0.05215155 0.9605018  0.80516314 0.24422996]
 [0.68127622 0.06764503 0.3799992  0.22165234]]
[[0.12200679 0.36650781 0.8296915 ]
 [0.9605018  0.80516314 0.24422996]
 [0.06764503 0.3799992  0.22165234]]


In [ ]:
uniform_random = np.random.rand(4, 5)
print(uniform_random)
print("Result")
print(uniform_random[2:,3:])

[[0.34683874 0.29961746 0.98921253 0.30279029 0.18983975]
 [0.78601871 0.15107351 0.53278371 0.74663633 0.3896812 ]
 [0.13240156 0.57167281 0.20694586 0.64905593 0.60139796]
 [0.76984861 0.77714967 0.68447657 0.23167174 0.57294626]]
Result
[[0.64905593 0.60139796]
 [0.23167174 0.57294626]]


# **4**
# **Introduction to Pandas Library for Data Analysis**

In [ ]:
pip install pandas

In [ ]:
import pandas as pd

Script 1:


In [ ]:
import pandas as pd
titanic_data=pd.read_csv("titanic_data.csv")
titanic_data.head()

FileNotFoundError: [Errno 2] No such file or directory: 'titanic_data.csv'

Script 2:

In [ ]:
titanic_pclass1=titanic_data.Pclass==1
print(titanic_pclass1)

Script 3:


In [ ]:
titanic_pclass1=titanic_data.Pclass==1
titanic_pclass1_data=titanic_data[titanic_pclass1]
titanic_pclass1_data.head()

Script 4:


In [ ]:
titanic_pclass1_data=titanic_data[titanic_data.Pclass==1]
titanic_pclass1_data.head()

Script 5:


In [ ]:
ages=[20,21,22]
age_dataset=titanic_data[titanic_data["Age"].isin(ages)]
age_dataset.head()

Script 6:


In [ ]:
ages=[20,21,22]
ageclass_dataset=titanic_data[titanic_data["Age"].isin(ages)&(titanic_data["Pclass"]==1)]
ageclass_dataset.head()

Script 7:


In [ ]:
titanic_data_filter=titanic_data.filter(["Name", "Sex","Age"])
titanic_data_filter.head()


Script 8:


In [ ]:
titanic_data_filter = titanic_data.drop(["Name", "Sex","Age"],axis=1)
titanic_data_filter.head()

Script 9:


In [ ]:
titanic_pclass1_data=titanic_data[titanic_data.Pclass==1]
print(titanic_pclass1_data.shape)

titanic_pclass2_data=titanic_data[titanic_data.Pclass==2]
print(titanic_pclass2_data.shape)


Script 10:


In [ ]:
final_data=titanic_pclass1_data.append(titanic_pclass2_data, ignore_index=True)
print(final_data)

Script 11:


In [ ]:
final_data=pd.concat([titanic_pclass1_data,titanic_pclass2_data])
print(final_data.shape)

Script 12:


In [ ]:
df1=final_data[:200]
print('---DF1---')
print(df1.shape)
print(df1.head())
print('------')

df2=final_data[200:]
print('---DF2---')
print(df2.shape)
print(df2.head())
print('------')

final_data2=pd.concat([df1,df2], axis=1, ignore_index=True)
print('---FINAL DATA---')
print(final_data2.shape)
print(final_data2.head())
print('------')

Script 13:


In [ ]:
age_sorted_data=titanic_data.sort_values(by=["Age"])
age_sorted_data.head()

Script 14:


In [ ]:
age_sorted_data=titanic_data.sort_values(by=["Age"],ascending=False)
age_sorted_data.head()

Script 15:


In [ ]:
age_sorted_data=titanic_data.sort_values(by=["Age","Fare"], ascending=False)
age_sorted_data.head()

Script 16:


In [ ]:
updated_class=titanic_data.Pclass.apply(lambda x:x+2)
updated_class.head()

Script 17:


In [ ]:
def mult(x):
  return x*2

updated_class=titanic_data.Pclass.apply(mult)
updated_class.head()

Script 18:


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

flights_data=sns.load_dataset('flights')
flights_data.head()

Script 19:


In [ ]:
flights_data_pivot=flights_data.pivot_table(index='month',columns='year',values='passengers')
flights_data_pivot.head()

Script 20:


In [ ]:
import pandas as pd
titanic_data=pd.read_csv('titanic_data.csv')
titanic_data.head()
pd.crosstab(titanic_data.Pclass, titanic_data.Age, margins=True)

Script 21:


In [ ]:
import numpy as np
titanic_data.head()
titanic_data.Fare=np.where(titanic_data.Age>20, titanic_data.Fare+5, titanic_data.Fare)
titanic_data.head()

**Exercise 4.1**

Question 1

In order to horizontally concatenate two Pandas dataframes, the value for the axis attribute should be set to:

A. 0

**B. 1**

C. 2

D. None of the above


Question 2

Which function is used to sort a Pandas dataframe by column value?

A. sort_dataframe()

B. sort_rows()

**C. sort_values()**

D. sort_records()


Question 3

To filter columns from a Pandas dataframe, you have to pass a list of column names to one of the following methods:

**A. filter()**

B. filter_columns()

C. apply_filter()

D. None of the above()


Exercise 4.2

Use the apply function to subtract 10 from the Fare column of the Titanic dataset, without using a lambda expression.

In [ ]:
import pandas as pd
titanic_data=pd.read_csv('titanic_data.csv')

def sub(x):
  return x-10

new_titanic_data=titanic_data.Fare.apply(sub)
print(new_titanic_data.head())
print('---')
print(titanic_data.head())

# **5**
# **Data Visualization via Matplotlib, Seaborn, and Pandas Libraries**

5.2. Data Visualization via Matplotlib


Script 1:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

x_vals=np.linspace(0,20,20)
y_vals=[math.sqrt(i) for i in x_vals]
plt.plot(x_vals,y_vals)

Script 2:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

x_vals=np.linspace(0,20,20)
y_vals=[math.sqrt(i) for i in x_vals]

fig=plt.figure()
ax=plt.axes()
ax.plot(x_vals,y_vals)

Script 3:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

plt.rcParams["figure.figsize"]=[8,6]

x_vals=np.linspace(0,20,20)
y_vals=[math.sqrt(i) for i in x_vals]
plt.plot(x_vals,y_vals)

Script 4:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

x_vals=np.linspace(0,20,20)
y_vals=[math.sqrt(i) for i in x_vals]

plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.title('Square Roots')

plt.plot(x_vals,y_vals)

Script 5:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

x_vals=np.linspace(0,20,20)
y_vals=[math.sqrt(i) for i in x_vals]

plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.title('Square Roots')

plt.plot(x_vals,y_vals,'r')

Script 6:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

x_vals=np.linspace(0,20,20)
y_vals=[math.sqrt(i) for i in x_vals]

plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.title('Square Roots')
plt.plot(x_vals,y_vals,'r',label='Square Root')
plt.legend(loc='upper center')

Script 7:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

x_vals=np.linspace(0,20,20)
y_vals=[math.sqrt(i)for i in x_vals]
y2_vals=x_vals**3

plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.title('Square Roots')
plt.plot(x_vals,y_vals,'r',label='Square Roots')
plt.plot(x_vals,y2_vals,'b', label='Cube')
plt.legend(loc='upper center')

Script 8:


In [ ]:
import pandas as pd
data=pd.read_csv('iris_data.csv')


Script 9:


In [ ]:
data.head()

Script 10:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

plt.xlabel('Sepal Length')
plt.ylabel('Petal Length')
plt.title('Sepal vs Petal Length')
plt.plot(data['sepal_length'],data['petal_length'],'b')

Script 11:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

plt.xlabel('Sepal Length')
plt.ylabel('Petal Length')
plt.title('Sepal vs Petal Length')
plt.scatter(data['sepal_length'],data['petal_length'],c='b')

Script 12:


In [ ]:
import pandas as pd
data=pd.read_csv('titanic_data.csv')
data.head()
data.shape

Script 13:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

plt.xlabel('Gender')
plt.ylabel('Ages')
plt.title('Gender vs Ages')
plt.bar(data['Sex'],data['Age'])
print(data['Age'].max())
print(data['Age'].max())

Script 16:


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import math

plt.title('Age Histogram')
plt.hist(data['Age'])

Script 17:


In [ ]:
labels='IT', 'Marketing','Data Science', 'Finance'
values=[500,156,300,510]
explode=(0.05,0.05,0.05,0.1)

plt.pie(values, explode=explode, labels=labels, autopct='1%.1f%%', shadow=True)
plt.show()

In [ ]:
pip install seaborn

Script 18:


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['figure.figsize']=[10,8]

tips_data=sns.load_dataset('tips')

tips_data.head()

Script 19:


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['figure.figsize']=[10,8]
sns.distplot(tips_data['total_bill'])

Script 20:


In [ ]:
sns.jointplot(x='total_bill',y='tip',data=tips_data)

Script 21:


In [ ]:
sns.jointplot(x='size',y='total_bill',data=tips_data,kind='reg')

Script 22:


In [ ]:
sns.pairplot(data=tips_data)

Script 23:

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams['figure.figsize']=[8,6]
sns.set_style('darkgrid')

titanic_data=sns.load_dataset('titanic')

titanic_data.head()

Script 24:


In [ ]:
sns.barplot(x='pclass',y='age', data=titanic_data)

Script 25:


In [ ]:
sns.countplot(x='pclass',data=titanic_data)

Script 26:


In [ ]:
sns.boxplot(x=titanic_data['age'])

Script 27:


In [ ]:
sns.violinplot(x='alone',y='age',data=titanic_data)

Script 28:


In [ ]:
import pandas as pd

titanic_data=pd.read_csv('titanic_data.csv')
titanic_data.head()

Script 29:


In [ ]:
import matplotlib.pyplot as plt
titanic_data['Age'].hist()

Script 30:


In [ ]:
flights_data=sns.load_dataset('flights')
flights_data.head()

Script 31:


In [ ]:
flights_data.plot.line(y='passengers',figsize=(8,6))

Script 32:


In [ ]:
flights_data.plot.scatter(x='year',y='passengers',figsize=(8,6))

Script 33:


In [ ]:
sex_mean=titanic_data.groupby('Sex')['Age'].mean()
print(sex_mean)
print(type(sex_mean.tolist()))

Script 34:


In [ ]:
df=pd.DataFrame({'Gender':['Famale','Male'],'Age':sex_mean.tolist()})
ax=df.plot.bar(x='Gender',y='Age',figsize=(8,6))

**Exercise 5.1**

**Question 1**

Which Pandas function is used to plot a horizontal bar plot:

A. horz_bar()

**B. barh()**

C. bar_horizontal()

D. horizontal_bar()



**Question 2:**

To create a legend, the value for which of the following parameters is needed to be specified?

A. title

**B. label**

C. axis

D. All of the above



**Question 3:**

How to show percentage values on a Matplotlib Pie Chart?

**A. autopct = ‘%1.1f%%’**

B. percentage = ‘%1.1f%%’

C. perc = ‘%1.1f%%’

D. None of the Above



**Exercise 5.2**

Plot two scatter plots on the same graph using the tips_dataset. In the first scatter plot, display values from the total_bill column on the x-axis and from the tip column on the y-axis. The color of the first scatter plot should be green.

In the second scatter plot, display values from the total_bill column on the x-axis and from the size column on the y-axis. The color of the second scatter plot should be blue, and markers should be x.

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

tips_data=sns.load_dataset('tips')
sns.scatterplot(x="total_bill", y="tip", data=tips_data, color = 'g')
sns.scatterplot(x="total_bill", y="size", data=tips_data, color = 'b', marker = 'x')





# **6**

# **Solving Regression Problems in Machine Learning Using Sklearn Librar**

Script 1:

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

sns.get_dataset_names()

Script 2:

In [ ]:
tips_df=sns.load_dataset('tips')
tips_df.head()

Script 3:

In [ ]:
diamond_df=sns.load_dataset('diamonds')
diamond_df.head()

Script 4:

In [ ]:
x=tips_df.drop(['tip'],axis=1)
y=tips_df['tip']

Script 5:

In [ ]:
x.head()


Script 6:

In [ ]:
y.head()

Script 7:

In [ ]:
numerical=x.drop(['sex','smoker','day','time'],axis=1)

Script 8:

In [ ]:
numerical.head()

Script 9:

In [ ]:
categorical=x.filter(['sex','smoker','day','time'])
categorical.head()

Script 10:

In [ ]:
import pandas as pd
cat_numerical=pd.get_dummies(categorical, drop_first=True,dtype=int)
cat_numerical.head()


Script 11:

In [ ]:
x=pd.concat([numerical,cat_numerical],axis=1)
x.head()

Script 12:


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=0)
x_train.head()

Script 13:


In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
#scaling the training set
x_train=sc.fit_transform(x_train)
#scaling the test set
x_test=sc.transform(x_test)
x_train.head()

Script 14:


In [ ]:
from sklearn.linear_model import LinearRegression
#traning the algorithm
lin_reg=LinearRegression()
regressor=lin_reg.fit(x_train, y_train)

#making predictionson test set
y_pred=regressor.predict(x_test)

Script 15:


In [ ]:
from sklearn import metrics

print('Mean Absolute Error: ',metrics.mean_absolute_error(y_test,y_pred))
print('Mean Squared Error: ', metrics.mean_squared_error(y_test,y_pred))
print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

plt.plot(x_test, y_test, color='red')

plt.plot(x_test, y_pred, color='blue')


EXAMPLE

In [ ]:
# Code source: Jaques Grobler
# License: BSD 3 clause

import matplotlib.pyplot as plt
import numpy as np

from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# Load the diabetes dataset
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)

# Use only one feature
diabetes_X = diabetes_X[:, np.newaxis, 2]

# Split the data into training/testing sets
diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:]

# Split the targets into training/testing sets
diabetes_y_train = diabetes_y[:-20]
diabetes_y_test = diabetes_y[-20:]

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(diabetes_X_train, diabetes_y_train)

# Make predictions using the testing set
diabetes_y_pred = regr.predict(diabetes_X_test)

# The coefficients
print("Coefficients: \n", regr.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(diabetes_y_test, diabetes_y_pred))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(diabetes_y_test, diabetes_y_pred))

# Plot outputs
plt.scatter(diabetes_X_test, diabetes_y_test, color="black")
plt.plot(diabetes_X_test, diabetes_y_pred, color="blue", linewidth=3)

plt.xticks(())
plt.yticks(())

plt.show()

Script 16:


In [ ]:
from sklearn.neighbors import KNeighborsRegressor
knn_reg=KNeighborsRegressor(n_neighbors=5)
regressor=knn_reg.fit(x_train,y_train)
import matplotlib.pyplot as plt

y_pred=regressor.predict(x_test)

from sklearn import metrics
print('Mean Absolute Error: ',metrics.mean_absolute_error(y_test,y_pred))
print('Mean Squared Error: ', metrics.mean_squared_error(y_test,y_pred))
print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

plt.plot(x_test, y_test, color='red')

plt.plot(x_test, y_pred, color='blue')


Script 17:


In [ ]:
#training and testing the random forest
from sklearn.ensemble import RandomForestRegressor
rf_reg=RandomForestRegressor(random_state=42,n_estimators=500)
regressor=rf_reg.fit(x_train,y_train)
y_pred=regressor.predict(x_test)

#evaluating algorithm performance
from sklearn import metrics
print('Mean Absolute Error: ',metrics.mean_absolute_error(y_test,y_pred))
print('Mean Squared Error: ', metrics.mean_squared_error(y_test,y_pred))
print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

Script 18:


In [ ]:
#training and testing the SVM

from sklearn import svm
svm_reg=svm.SVR()

regressor=svm_reg.fit(x_train,y_train)
y_pred=regressor.predict(x_test)

#evaluating algorithm performance
from sklearn import metrics
print('Mean Absolute Error: ',metrics.mean_absolute_error(y_test,y_pred))
print('Mean Squared Error: ', metrics.mean_squared_error(y_test,y_pred))
print('Root Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

Script 19:


In [ ]:
from sklearn.model_selection import cross_val_score
print(cross_val_score(regressor,x,y,cv=5,scoring='neg_mean_absolute_error'))

Script 20:


In [ ]:
tips_df.loc[100]

Script 21:


In [ ]:
from sklearn.ensemble import RandomForestRegressor
rf_reg=RandomForestRegressor(random_state=42,n_estimators=500)
regressor=rf_reg.fit(x_train,y_train)
single_record=sc.transform(x.values[100].reshape(1,-1))
predicted_tip=regressor.predict(single_record)
print(predicted_tip)


**Exercise 6.1**

**Question 1**

Among the following, which one is an example of a regression output?

A. True

B. Red

**C. 2.5**

D. None of the above



**Question 2**

Which of the following algorithm is a lazy algorithm?

A. Random Forest

**B. KNN**

C. SVM

D. Linear Regression



**Question 3**
Which of the following algorithm is not a regression metric?

A. Accuracy

B. Recall

C. F1 Measure

**D. All of the above**


**Exercise 6.2**

Using the Diamonds dataset from the Seaborn library, train a regression algorithm of your choice, which predicts the price of the diamond. Perform all the preprocessing steps.

In [ ]:
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor
from sklearn import svm
from sklearn import metrics
import numpy as np

#step 1: crear data frame de datos
diamonds_df=sns.load_dataset('diamonds')


#step 2: generar las listas del data frame x e y
x=diamonds_df.drop(['price'],axis=1)
y=diamonds_df['price']

#step 3: genear el data frame de numeros
  #step 3.1: separar el texto de numeros
numerical=x.drop(['cut','color','clarity'],axis=1)
categorical=x.filter(['cut','color','clarity'])

  #step 3.2: convertir el texto a numeros que se puedan manejar
cat_numerical=pd.get_dummies(categorical, drop_first=True,dtype=int)

  #step 3.3: unir los 2 dataframe de solo numeros
x=pd.concat([numerical,cat_numerical],axis=1)


#step 4: generar los datos para entrenamiento y testeo
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=0)

#step 5: normalizar los valores
sc=StandardScaler()
  #scaling the training set
x_train=sc.fit_transform(x_train)
  #scaling the test set
x_test=sc.transform(x_test)


#step 6: aplicar los algoritmos

#--LinearRegression--
#traning the algorithm
lin_reg=LinearRegression()
regressor=lin_reg.fit(x_train, y_train)
#making predictionson test set
y_pred_ln=regressor.predict(x_test)


#--KNeighborsRegressor--
#traning the algorithm
knn_reg=KNeighborsRegressor(n_neighbors=5)
regressor=knn_reg.fit(x_train,y_train)
#making predictionson test set
y_pred_kn=regressor.predict(x_test)


#--RandomForestRegressor--
#traning the algorithm
rf_reg=RandomForestRegressor(random_state=42,n_estimators=500)
regressor=rf_reg.fit(x_train,y_train)
#making predictionson test set
y_pred_rf=regressor.predict(x_test)


#--SVM--
#traning the algorithm
svm_reg=svm.SVR()
regressor=svm_reg.fit(x_train,y_train)
#making predictionson test set
y_pred_svm=regressor.predict(x_test)


y_pred=[y_pred_ln,y_pred_kn,y_pred_rf,y_pred_svm]
algoritmo=['--LinearRegression--','--KNeighborsRegressor--','--RandomForestRegressor--','--SVM--']
for x in range(0,4):
  print(algoritmo[x])
  print('\tMean Absolute Error: ',metrics.mean_absolute_error(y_test,y_pred[x]))
  print('\tMean Squared Error: ', metrics.mean_squared_error(y_test,y_pred[x]))
  print('\tRoot Mean Squared Error: ', np.sqrt(metrics.mean_squared_error(y_test,y_pred[x])))
  print('\n')






RESPUESTA DEL LIBRO


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

diamonds_df = sns.load_dataset("diamonds")

X = diamonds_df.drop(['price'], axis=1)

y = diamonds_df["price"]

numerical = X.drop(['cut', 'color', 'clarity'], axis = 1)

categorical = X.filter(['cut', 'color', 'clarity'])

cat_numerical = pd.get_dummies(categorical,drop_first=True)

X = pd.concat([numerical, cat_numerical], axis = 1)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform (X_test)

from sklearn import svm
svm_reg = svm.SVR()
regressor = svm_reg.fit(X_train, y_train)
y_pred = regressor.predict(X_test)

from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

# **7**

# **Solving Classification Problems in Machine Learning Using Sklearn Library**

Script 1:


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns


Script 2:


In [ ]:
# Se crea el DataFrame de los datos
churn_df=pd.read_csv('customer_churn.csv')
churn_df.head()

Script 3:


In [ ]:
#Se elimina las columnas que no son necesarias para hacer predicciones
churn_df=churn_df.drop(['RowNumber','CustomerId','Surname'], axis=1)


Script 4:


In [ ]:
#Se divide el DataFrame entre las columnas a predecir (y) y el resto (x)
x=churn_df.drop(['Exited'], axis=1)
y=churn_df['Exited']

Script 5:

In [ ]:
x.head()

Script 6:

In [ ]:
y.head()

Script 7:

In [ ]:
#Separar las columnas con numeros del Dataframe original
numerical=x.drop(['Geography','Gender'],axis=1)

Script 8:

In [ ]:
numerical.head()

Script 9:


In [ ]:
#Separar las columnas categoricas dle DataFrame original
categorical=x.filter(['Geography','Gender'])
categorical.head()

Script 10:


In [ ]:
#Transformar el DataFrame de datos categoricos en 1 y 0
cat_numerical=pd.get_dummies(categorical, drop_first=True, )
#cat_numerical=pd.get_dummies(categorical, drop_first=True,dtype=int)
cat_numerical.head()

Script 11:


In [ ]:
#Unir los DataFrame que solo son numericos para el analisis
x=pd.concat([numerical,cat_numerical],axis=1)
x.head()

Script 12:


In [ ]:
#Dividir el DataFrame en datos para entrenar (train) y para testear el modelo (test)
from sklearn.model_selection import train_test_split

#test size is the fraction of the test size
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

Script 13:


In [ ]:
#Normalizar los datos del DataFrame
from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)


Script 14:


In [ ]:
#--LogisticRegression--
from sklearn.linear_model import LogisticRegression

log_clf=LogisticRegression()
#train
classifier=log_clf.fit(x_train,y_train)
#test
y_pred=classifier.predict(x_test)

Script 15:


In [ ]:
#Determinar la presicion del modelo
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
con_mat=confusion_matrix(y_test,y_pred)
cla_rep=classification_report(y_test,y_pred)
acc_sco=accuracy_score(y_test,y_pred)
print('Confusion matrix: \n',con_mat)
print('Classification report: \n',cla_rep)
print('Accuracy: ',acc_sco)



In [ ]:
#Grafico de Matriz de Confusion
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay
disp = ConfusionMatrixDisplay(confusion_matrix=con_mat,display_labels=log_clf.classes_)
disp.plot()
plt.show()

#Grafico Presicion vs. Recall
from sklearn.metrics import (precision_recall_curve, PrecisionRecallDisplay)
PrecisionRecallDisplay.from_predictions(y_test, y_pred)
plt.show()

Script 16:


In [ ]:
#--KNeighborsClassifier--
from sklearn.neighbors import KNeighborsClassifier

knn_clf=KNeighborsClassifier(n_neighbors=5)
#train
classifier=knn_clf.fit(x_train,y_train)
#test
y_pred=classifier.predict(x_test)

#Determinar la presicion del modelo
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
con_mat=confusion_matrix(y_test,y_pred)
cla_rep=classification_report(y_test,y_pred)
acc_sco=accuracy_score(y_test,y_pred)
print('Confusion matrix: \n',con_mat)
print('Classification report: \n',cla_rep)
print('Accuracy: ',acc_sco)

#Grafico de Matriz de Confusion
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay
disp = ConfusionMatrixDisplay(confusion_matrix=con_mat,display_labels=knn_clf.classes_)
disp.plot()
plt.show()

#Grafico Presicion vs. Recall
from sklearn.metrics import (precision_recall_curve, PrecisionRecallDisplay)
PrecisionRecallDisplay.from_predictions(y_test, y_pred)
plt.show()


Script 17:


In [ ]:
#--RandomForestClassifier--
from sklearn.ensemble import RandomForestClassifier

rf_clf=RandomForestClassifier(random_state=42,n_estimators=500)

#train
classifier=rf_clf.fit(x_train,y_train)
#test
y_pred=classifier.predict(x_test)

#Determinar la presicion del modelo
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
con_mat=confusion_matrix(y_test,y_pred)
cla_rep=classification_report(y_test,y_pred)
acc_sco=accuracy_score(y_test,y_pred)
print('Confusion matrix: \n',con_mat)
print('Classification report: \n',cla_rep)
print('Accuracy: ',acc_sco)

#Grafico de Matriz de Confusion
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay
disp = ConfusionMatrixDisplay(confusion_matrix=con_mat,display_labels=rf_clf.classes_)
disp.plot()
plt.show()

#Grafico Presicion vs. Recall
from sklearn.metrics import (precision_recall_curve, PrecisionRecallDisplay)
PrecisionRecallDisplay.from_predictions(y_test, y_pred)
plt.show()



Script 18:


In [ ]:
#--SVM--
from sklearn import svm

svm_clf=svm.SVC()

#train
classifier=svm_clf.fit(x_train,y_train)
#test
y_pred=classifier.predict(x_test)

#Determinar la presicion del modelo
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
con_mat=confusion_matrix(y_test,y_pred)
cla_rep=classification_report(y_test,y_pred)
acc_sco=accuracy_score(y_test,y_pred)
print('Confusion matrix: \n',con_mat)
print('Classification report: \n',cla_rep)
print('Accuracy: ',acc_sco)

#Grafico de Matriz de Confusion
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay
disp = ConfusionMatrixDisplay(confusion_matrix=con_mat,display_labels=svm_clf.classes_)
disp.plot()
plt.show()

#Grafico Presicion vs. Recall
from sklearn.metrics import (precision_recall_curve, PrecisionRecallDisplay)
PrecisionRecallDisplay.from_predictions(y_test, y_pred)
plt.show()

Script 19:


In [ ]:
from sklearn.model_selection import cross_val_score

print(cross_val_score(classifier,x,y,cv=5,scoring='accuracy'))

Script 20:


In [ ]:
#Para predecir un valor solo
churn_df.loc[100]


Script 21:


In [ ]:
#entrenar el modelo con RandomForest
from sklearn.ensemble import RandomForestClassifier

rf_clf=RandomForestClassifier(random_state=42,n_estimators=500)
classifier=rf_clf.fit(x_train,y_train)

# scaling single record
single_record=sc.transform(x.values[100].reshape(1,-1))

#making predictions on the single record
predicted_churn = classifier.predict(single_record)
print(predicted_churn)

**Exercise 7.1**


**Question 1**

Among the following, which one is not an example of classification outputs?

A. True

B. Red

C. Male

**D. None of the above**



**Question 2**

Which of the following metrics is used for unbalanced classification datasets?

A. Accuracy

B. F1

**C. Precision**

D. Recall



**Question 3**

Among the following functions, which one is used to convert categorical values to one-hot encoded numerical values?

A. pd.get_onehot()

**B. pd.get_dummies()**

C. pd.get_numeric()

D. All of the above



**Exercise 7.2**

Using the iris dataset from the Seaborn library, train a classification algorithm of your choice, which predicts the species of the iris plant. Perform all the preprocessing steps.

In [ ]:
import seaborn as sns
iris_df=sns.load_dataset('iris')
iris_df.head()

In [ ]:
import seaborn as sns
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
from sklearn import metrics
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import ConfusionMatrixDisplay
from sklearn.metrics import (precision_recall_curve, PrecisionRecallDisplay)

#step 1: crear data frame de datos
iris_df=sns.load_dataset('iris')


#step 2: generar las listas del data frame x e y
x=iris_df.drop(['species'],axis=1)
y=iris_df['species']

#step 3: genear el data frame de numeros
  #step 3.1: separar el texto de numeros


  #step 3.2: convertir el texto a numeros que se puedan manejar


  #step 3.3: unir los 2 dataframe de solo numeros



#step 4: generar los datos para entrenamiento y testeo
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=0)

#step 5: normalizar los valores
sc=StandardScaler()
  #scaling the training set
x_train=sc.fit_transform(x_train)
  #scaling the test set
x_test=sc.transform(x_test)


#step 6: aplicar los algoritmos

#--LogisticRegression--
log_clf=LogisticRegression()
#train
classifier=log_clf.fit(x_train,y_train)
#test
y_pred_lg=classifier.predict(x_test)


#--KNeighborsClassifier--
knn_clf=KNeighborsClassifier(n_neighbors=5)
#train
classifier=knn_clf.fit(x_train,y_train)
#test
y_pred_kn=classifier.predict(x_test)


#--RandomForestClassifier--
rf_clf=RandomForestClassifier(random_state=42,n_estimators=500)
#train
classifier=rf_clf.fit(x_train,y_train)
#test
y_pred_rf=classifier.predict(x_test)


#--SVM--
svm_clf=svm.SVC()
#train
classifier=svm_clf.fit(x_train,y_train)
#test
y_pred_svm=classifier.predict(x_test)





y_pred=[y_pred_lg,y_pred_kn,y_pred_rf,y_pred_svm]
modelo=[log_clf,knn_clf,rf_clf,svm_clf]
algoritmo=['--LogisticRegression--','--KNeighborsClassifier--','--RandomForestClassifier--','--SVM--']

for x in range(0,4):
  #Determinar la presicion del modelo
  print('--',algoritmo[x],'--')
  con_mat=confusion_matrix(y_test,y_pred[x])
  cla_rep=classification_report(y_test,y_pred[x])
  acc_sco=accuracy_score(y_test,y_pred[x])
  print('Confusion matrix: \n',con_mat)
  print('Classification report: \n',cla_rep)
  print('Accuracy: ',acc_sco)

  #Grafico de Matriz de Confusion
  disp = ConfusionMatrixDisplay(confusion_matrix=con_mat,display_labels=modelo[x].classes_)
  disp.plot()
  plt.show()








RESPUESTA DEL LIBRO

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

iris_df = sns.load_dataset("iris")

iris_df.head()

X = iris_df.drop(['species'], axis=1)
y = iris_df["species"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform (X_test)
from sklearn.ensemble import RandomForestClassifier
rf_clf = RandomForestClassifier(random_state=42, n_estimators=500)

classifier = rf_clf.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

con_mat=confusion_matrix(y_test,y_pred)
cla_rep=classification_report(y_test,y_pred)
acc_sco=accuracy_score(y_test,y_pred)
print('Confusion matrix: \n',con_mat)
print('Classification report: \n',cla_rep)
print('Accuracy: ',acc_sco)



# **8**

# **Data Clustering with Machine Learning Using Sklearn Library**

Script 1:


In [ ]:
#Importing the libraries needed is the first step
import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from matplotlib import pyplot as plt
%matplotlib inline

Script 2:


In [ ]:
#Next, we create a dummy dataset containing 500 records and 4 cluster centers. The average standard deviation between the records is 2.0.
#The following script creates a dummy dataset and plots data points on a plot.

#generating dummydata of 500 records whit 4 cluster
from sklearn.datasets import make_blobs
features,cluster=make_blobs(n_samples=500,centers=4,cluster_std=2.00)

#plotting the dummy data
plt.scatter(features[:,0],features[:,1])

Script 3:

In [ ]:
#performing kmeans clustering using KMeans class
km_model=KMeans(n_clusters=4)
km_model.fit(features)

Script 4:

In [ ]:
#printing centroid values
print(km_model.cluster_centers_)

Script 5:

In [ ]:
#For instance, in the case of four clusters, the cluster ids are 0,1,2,3.
#To print the cluster ids for all the labels, you can use the labels_attribute of the KMeans class, as shown below.

#printing predicted label values
print(km_model.labels_)
print(len(km_model.labels_))

Script 6:


In [ ]:
#The following script prints the clusters in different colors along with the cluster centers as black data points, as shown below.

#pring the data point
plt.scatter(features[:,0],features[:,1],c=km_model.labels_,cmap='rainbow')

#print the centroids
plt.scatter(km_model.cluster_centers_[:,0], km_model.cluster_centers_[:,1],c='black')

Script 7:


In [ ]:
#The following script prints the actual four clusters in the dataset.

#print actual datapoint
plt.scatter(features[:,0],features[:,1],c=km_model.labels_,cmap='rainbow')

Script 8:


In [ ]:
#The Iris dataset can be imported via the following script
import seaborn as sns

iris_df=sns.load_dataset('iris')
iris_df.head()

Script 9:


In [ ]:
#We do not use data labels for clustering. Hence, we will separate features from labels

#dividing data into features and labels

features=iris_df.drop(['species'],axis=1)
lables=iris_df.filter(['species'],axis=1)
features.head()


Script 10:

In [ ]:
#Let’s first choose 4 as a random number for the number of clusters.
#The following script performs K Means clustering on the Iris dataset

#trainig KMeans model
#features=features.values()
km_model=KMeans(n_clusters=4)
km_model.fit(features)

Script 11:

In [ ]:
#To print labels of the Iris dataset, execute the following script

print(km_model.labels_)

Script 12:

In [ ]:
#Finally, to plot the 4 clusters found by the K Means algorithm in the Iris dataset, along with the predicted cluster centroids, execute the following script

#print the datapoint
plt.scatter(features[:,0],features[:,1],c=km_model.labels_,cmap='rainbow')

#print the centroids
plt.scatter(km_model.cluster_centers_[:,0],km_model.cluster_centers_[:,1],s=100,c='black')


Script 13:

In [ ]:
#To calculate the inertia value, you can use the inertia_ attribute of the KMeans class object.
#The following script creates inertial values for K=1 to 10 and plots in the form of a line plot, as shown below

#trainig KMeans on K values from 1 to 10
loss=[]
for i in range(1,11):
  km=KMeans(n_clusters=i).fit(features)
  loss.append(km.inertia_)

#printing loss against number of clusters

import matplotlib.pyplot as plt
plt.plot(range(1,11),loss)
plt.title('Finding Optimal Clusters via Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('Loss')
plt.show()

From the output below, it can be seen that the value of inertia didn’t decrease much after 3 clusters.

Script 14:

In [ ]:
#Let’s now cluster the Iris data using 3 clusters and see if we can get close to the actual clusters

#training KMeans with 3 clusters
km_model=KMeans(n_clusters=3)
km_model.fit(features)



Script 15:

In [ ]:
# print the datapoint with prediced labels
plt.scatter(features[:,0],features[:,1],c=km_model.labels_,cmap='rainbow')

#print the predicted centroids
plt.scatter(km_model.cluster_centers_[:,0],km_model.cluster_centers_[:,1],s=100,c='black')

Script 16:

In [ ]:
#Let’s now plot the actual clusters and see how close the actual clusters are to predicted clusters

#converting categorical labels to numbers
#from sklearn import preprocessing
#le=preprocessing.LabelEncoder()
#labels=le.fit_transform(labels)

#print the data poin with the orgonal labels
plt.scatter(features[:,0], features[:,1], c=km_model.labels_,cmap='rainbow')

Script 17:

In [ ]:
#The following script imports the required libraries:

import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs
from matplotlib import pyplot as plt
%matplotlib inline

Script 18:

In [ ]:
#The following script randomly creates data points and then labels the data points from 1 to 10. The data points are plotted as a scatter plot.

#generating dummy data of 10 records with 2 clusters
features, labels=make_blobs(n_samples=10,centers=2,cluster_std=2)
print('FEATURES: ',features)
print('LABELS: ', labels)

#plotting the dummy data
plt.scatter(features[:,0], features[:,1],color='r')

#adding number to data points
annots=range(1,11)
for label,x,y in zip(annots,features[:,0],features[:,1]):
  plt.annotate(label,xy=(x,y),xytext=(-3,3),textcoords='offset points',ha='right',va='bottom')
plt.show()



Script 19:

In [ ]:
#Let’s now plot dendrograms for the above 10 data points. To
#plot dendrograms, you can use the dendrogram and linkage
#classes from the scipy.cluster.hierarchy module. The features
#are passed to the linkage class. And the object of the linkage
#class is passed to the dendrogram class to plot dendrogram
#for the features, as shown in the following script:

from scipy.cluster.hierarchy import dendrogram, linkage

dendos=linkage(features, 'single')

annots=range(1,11)

dendrogram(dendos, orientation='top', labels=annots,distance_sort='descending',show_leaf_counts=True)

plt.show()



Script 20:

In [ ]:
#The following script applies agglomerative clustering to our dummy dataset.

from sklearn.cluster import AgglomerativeClustering

#trainingagglomerative clustering model
hc_model =AgglomerativeClustering(n_clusters=3,affinity='euclidean',linkage='ward')
hc_model.fit(features)

Script 21:

In [ ]:
#And the following script plots the predicted clusters.

#print the data point
plt.scatter(features[:,0],features[:,1],c=hc_model.labels_,cmap='rainbow')
#adding number to data points
annots=range(1,11)
for label,x,y in zip(annots,features[:,0],features[:,1]):
  plt.annotate(label,xy=(x,y),xytext=(-3,3),textcoords='offset points',ha='right',va='bottom')
plt.show()

Script 22:

In [ ]:
#The following script creates 500 data points with 4 cluster centers.

#generating dummy data of 500 records with 4 clusters
features, labels=make_blobs(n_samples=500,centers=4,cluster_std=2)

#plotting the dummy data
plt.scatter(features[:,0],features[:,1])

Script 23:

In [ ]:
#The following script applies agglomerative hierarchical clustering on the dataset. The number of predicted clusters is 4.

#performing kmeans clustering using AgglomerativeClustering class

from sklearn.cluster import AgglomerativeClustering
hc_model=AgglomerativeClustering(n_clusters=4,affinity='euclidean',linkage='ward')
hc_model.fit_predict(features)

Script 24:

In [ ]:
#To plot the predicted clusters, execute the following script.

#print the data point

plt.scatter(features[:,0],features[:,1],c=hc_model.labels_,cmap='rainbow')

Script 25:

In [ ]:
#Similarly, to plot the actual clusters in the dataset (for the sake of comparison), execute the following script.

#print actual data point
plt.scatter(features[:,0], features[:,1],c=labels, cmap='rainbow')

Script 26:

In [ ]:
#The following script imports the Iris dataset and displays the first five rows of the dataset.

import seaborn as sns

iris_df=sns.load_dataset('iris')
iris_df.head()

Script 27:

In [ ]:
#The following script divides the data into features and labels sets and displays the first five rows of the labels set.

#dividing data into features and labels

features=iris_df.drop(['species'],axis=1)
labels=iris_df.filter(['species'],axis=1)
features.head()

Script 28:

In [ ]:
#Similarly, the following script applies the agglomerative clustering on the feature set using the AgglomerativeClustering class from the sklearn.cluster module.

#training hierarchical clustering model
from sklearn.cluster import AgglomerativeClustering

#traning agglomerative clustering model
features=features.values
hc_model=AgglomerativeClustering(n_clusters=3,affinity='euclidean',linkage='ward')
hc_model.fit_predict(features)

Script 29:

In [ ]:
#The predicted clusters are printed via the following script.

#print the data point

plt.scatter(features[:,0],features[:,1],c=hc_model.labels_,cmap='rainbow')


Script 30:

In [ ]:
import scipy.cluster.hierarchy as shc

plt.figure(figsize=(10,7))
plt.title('Iris dendograms')

dend=shc.dendrogram(shc.linkage(features,method='ward'))

**Exercise 8.1**

**Question 1**

Which of the following is a supervised machine learning algorithm?

A. K Means Clustering

B. Hierarchical Clustering

C. All of the above

**D. None of the above**




Question 2

In KMeans clustering, what does the inertia tell us?

A. the distance between data points within cluster

B. output labels for the data points

**C. the number of clusters**

D. None of the above




Question 3

In hierarchical clustering, in the case of vertical dendrograms, the number of clusters is equal to the number of ____ lines that the ____ line passes through?

A. horizontal, vertical

**B. vertical, horizontal**

C. none of the above

D. All of the above



**Exercise 8.2**

Apply KMeans clustering on the banknote.csv dataset available in the Data folder in the book resources. Find the optimal number of clusters and then print the clustered dataset.

In [ ]:
#STEP 1: IMPORT LIBRARIES
import numpy as np
import pandas as pd
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans
from matplotlib import pyplot as plt
%matplotlib inline

#STEP 2: IMPORT DATA
data_df=pd.read_csv('banknote.csv')


#STEP 3: DIVIDING DATA INTO FEATURES AND LABELS
features=data_df.drop(['class'],axis=1)
labels=data_df.filter(['class'],axis=1)


#STEP 4: DETERMINATE THE OPTIMAL NUMBER OF CLUSTER
  #trainig KMeans on K values from 1 to 100
loss=[]
for i in range(1,101):
  km=KMeans(n_clusters=i).fit(features)
  loss.append(km.inertia_)

  #printing loss against number of clusters
plt.plot(range(1,101),loss)
plt.title('Finding Optimal Clusters via Elbow Method')
plt.xlabel('Number of Clusters')
plt.ylabel('Loss')
plt.show()

#STEP 5: TRANING KMEANS WITH 20 CLUSTERS
features = features.values
km_model=KMeans(n_clusters=10)
km_model.fit(features)


#STEP 6: PRINT THE DATAPOINT
  # print the datapoint with prediced labels
plt.scatter(features[:,0],features[:,1],c=km_model.labels_,cmap='rainbow')
  #print the predicted centroids
plt.scatter(km_model.cluster_centers_[:,0],km_model.cluster_centers_[:,1],s=100,c='black')


# **9**
# **Deep Learning with**
# **Python TensorFlow 2.0**

**9.1. Densely Connected Neural Network**

Script 1:

In [ ]:
#The following script upgrades the existing TensorFlow version.

pip install --upgrade tensorflow

Script 2:

In [ ]:
#To check if you are actually running TensorFlow 2.0

import tensorflow as tf
print(tf.__version__)

Script 3: Importing Required Libraries

In [ ]:
#Let’s import the required libraries.

import seaborn as sns
import pandas as pd
import numpy as np
from tensorflow.keras.layers import Dense,Dropout,Activation
from tensorflow.keras.models import Model,Sequential
from tensorflow.keras.optimizers import Adam

Script 4: Importing the Dataset

In [ ]:
#Importing the dataset

#reading data from csv file
banknote_data=pd.read_csv('banknote.csv')

Script 5:

In [ ]:
#The following script plots the first five rows of the dataset.

banknote_data.head()

Script 6:

In [ ]:
#Let’s see the shape of our dataset

banknote_data.shape

Script 7:

In [ ]:
#Let’s plot a count plot to see the distribution of data with respect to the values in the class that we want to predict.

sns.countplot(x='class', data=banknote_data)

Script 8:

In [ ]:
#Let’s divide our data into features and target labels.

x=banknote_data.drop(['class'],axis=1)
y=banknote_data[['class']].values

print(x.shape)
print(y.shape)

Script 9: Dividing Data into Training and Test Sets

In [ ]:
#We will divide the total data into an 80 percent training set
#and a 20 percent test set. The following script performs that task.

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2, random_state=42)

Script 10:

In [ ]:
#Before you train your deep learning model, it is always a
#good practice to scale your data. The following script applies
#standard scaling to the training and test sets.

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

Script 11: Creating a Neural Network

In [ ]:
def create_model (learning_rate,dropout_rate):
  #create sequential model
  model=Sequential()
  #adding dense layers
  model.add(Dense(12,input_dim=x_train.shape[1], activation='relu'))
  model.add(Dropout(dropout_rate))
  model.add(Dense(6,activation='relu'))
  model.add(Dropout(dropout_rate))
  model.add(Dense(1, activation='sigmoid'))
  #compiling the model
  adam=Adam(lr=learning_rate)
  model.compile(loss='binary_crossentropy',optimizer=adam,metrics=['accuracy'])
  return model

Script 12:

In [ ]:
dropout_rate=0.1
epochs=20
batch_size=4
learn_rate=0.001

model=create_model(learn_rate,dropout_rate)

Script 13:

In [ ]:
#You can see your model architecture via the plot_model() method of the tensorflow.keras.utils module.

from tensorflow.keras.utils import plot_model
plot_model(model,to_file='model_plot1.png',show_shapes=True,show_layer_names=True)

Script 14:

In [ ]:
model_history=model.fit(x_train,y_train,batch_size=batch_size,epochs=epochs,validation_split=0.2,verbose=1)

Script 15: Evaluating the Neural Network Performance

In [ ]:
#To make predictions on the test set, you have to pass
#the set to the evaluate() method of the model

accuracies=model.evaluate(x_test,y_test,verbose=1)
print('Test Score',accuracies[0])
print('Test Accuracy',accuracies[1])

Script 16:

In [ ]:
# Let’s now plot the accuracy on the training and test sets to see
#if our model is overfitting or not.

from matplotlib import pyplot as plt

plt.plot(model_history.history['accuracy'],label='accuracy')
plt.plot(model_history.history['val_accuracy'],label='val_accuracy')
plt.legend(['train','test'],loc='lower left')

Script 17:

In [ ]:
#Similarly, the loss values for test and training sets can be
#printed as follows:

plt.plot(model_history.history['loss'],label='loss')
plt.plot(model_history.history['val_loss'],label='val_loss')
plt.legend(['train','test'],loc='upper left')

**9.2. Recurrent Neural Networks (RNN)**

In this section, we will predict the opening stock price of the
Facebook company, using the opening stock price of the
previous 60 days.

Script 18:

In [ ]:
#Before you train the stock market prediction model, upload the TensorFlow version

#pip install --upgrade tensorflow
import tensorflow as tf
print(tf.__version__)

Script 20:

In [ ]:
#Next, to import the training dataset, execute the following script:

#importing libraries
import pandas as pd
import numpy as np

#imporing dataset
fb_complete_data=pd.read_csv('fb_train.csv')

Script 21:

In [ ]:
#printing dataset header
fb_complete_data.head()

Script 22:

In [ ]:
#The output shows that our dataset consists of seven columns.
#However, in this section, we are only interested in the Open
#column. Therefore, we will select the Open column from the
#dataset

#filtering open column
fb_training_processed=fb_complete_data[['Open']].values

Script 23:

In [ ]:
#Next, we will scale our dataset.

#scaling features
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(0,1))

fb_training_scaled=scaler.fit_transform(fb_training_processed)

Script 24:

In [ ]:
print(len(fb_training_scaled))
print(fb_training_scaled)
print(fb_training_scaled[0,0])

Script 25:

In [ ]:
#Based on the opening stock prices of the previous days, we will be predicted the
#opening stock price for the next day.

#training features contain data of last 60 days
#training labels contain data of 61st day

fb_training_features=[]
fb_training_labels=[]

for i in range(60, len(fb_training_scaled)):
  fb_training_features.append(fb_training_scaled[i-60:i,0])
  fb_training_labels.append(fb_training_scaled[i,0])


Script 26:

In [ ]:
#We need to convert our data into Numpy array before we can use as input with Keras

#converting training data to numpy array
x_train=np.array(fb_training_features)
y_train=np.array(fb_training_labels)

Script 27:

In [ ]:
print(x_train.shape)
print(y_train.shape)

Script 28:

In [ ]:
#We need to reshape our input features into 3-dimensional format.

#converting data into 3d shape
x_train=np.reshape(x_train,(x_train.shape[0],x_train.shape[1],1))

Script 29:

In [ ]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input,Activation, Dense, Flatten, Dropout, LSTM
from tensorflow.keras.models import Model

Script 30:

In [ ]:
#defining the LSTM network

input_layer=Input(shape=(x_train.shape[1],1))
lstm1=LSTM(100,activation='relu', return_sequences=True)(input_layer)
do1=Dropout(0.2)(lstm1)

lstm2=LSTM(100,activation='relu', return_sequences=True)(do1)
do2=Dropout(0.2)(lstm2)

lstm3=LSTM(100,activation='relu', return_sequences=True)(do2)
do3=Dropout(0.2)(lstm3)

lstm4=LSTM(100,activation='relu')(do3)
do4=Dropout(0.2)(lstm4)

output_layer=Dense(1)(do4)
model=Model(input_layer,output_layer)
model.compile(optimizer='adam',loss='mse')


Script 31:

In [ ]:
#Next, we need to convert the output y into a column vector.

print(x_train.shape)
print(y_train.shape)
y_train=y_train.reshape(-1,1)
print(y_train.shape)

Script 32:

In [ ]:
#The following script trains our stock price prediction model on the training set.

#training model
model_history=model.fit(x_train,y_train,epochs=100,verbose=1,batch_size=32)

Script 33:

In [ ]:
#Let’s first import the data and then remove all the columns from the test data except the Open column.

#creating test set
fb_testing_complete_data=pd.read_csv('fb_test.csv')
fb_testing_processed=fb_testing_complete_data[['Open']].values


Script 34:

In [ ]:
#Let’s concatenate the training and test sets.

fb_all_data=pd.concat((fb_complete_data['Open'],fb_testing_complete_data['Open']),axis=0)

Script 35:

In [ ]:
test_input=fb_all_data[len(fb_all_data)-len(fb_testing_complete_data)-60:].values
print(test_input.shape)

Script 36:

In [ ]:
#We need to scale our data and convert it into a column vector.

test_input=test_input.reshape(-1,1)
test_input=scaler.transform(test_input)
print(test_input.shape)

Script 37:

In [ ]:
#we need to divide our input data into features and labels.

fb_test_features=[]
for i in range(60,80):
  fb_test_features.append(test_input[i-60:i,0])

Script 38:

In [ ]:
x_test=np.array(fb_test_features)
print(x_test.shape)

Script 39:

In [ ]:
#Our feature set is currently 2-dimensional. But the LSTM
#algorithm in Keras accepts only data in 3-dimensional. The
#following script converts our input features into a 3-dimensional
#shape.

#converting test data into 3d shape

x_test=np.reshape(x_test,(x_test.shape[0],x_test.shape[1],1))
print(x_test.shape)

Script 40:

In [ ]:
#Now is the time to make predictions on the test set.

#making prediction on test set
y_pred=model.predict(x_test)
print(y_pred.shape)

Script 41:

In [ ]:
#Since we scaled our input feature, we need to apply the
#inverse_transform() method of the scaler object on the
#predicted output to get the original output values

#coverting scaled data back to original data
#a = np.arange(6).reshape((3, 2))
#y_pred=y_pred.reshape(20,60)
#print(y_pred.shape)
y_pred=scaler.inverse_transform(y_pred)


Script 42:

In [ ]:
#plotting original and predicted stock values
plt.figure(figsize=(8,6))
plt.plot(fb_testing_processed, color='red',label='Actual Facebook Stock Price')
plt.plot(y_pred,color='green',label='Predicted Facebook Stock Price')
plt.title('Facebook Stock Price')
plt.xlabel('Date')
plt.ylabel('Stock Price')
plt.legend()
plt.show()

**9.3. Convolutional Neural Network**

Script 43:

In [ ]:


import tensorflow as tf
print(tf.__version__)

Script 44:

In [ ]:
#importing required libraries
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Input, Conv2D, Dense, Flatten, Dropout, MaxPool2D
from tensorflow.keras.models import Model

Script 45:

In [ ]:
#The following script downloads the Fashion MNIST dataset
#that contains images of different fashion items along with
#their labels. The script divides the data into training images
#and training labels and test images and test labels.

#importing mnist dataset
mnist_data=tf.keras.datasets.fashion_mnist

#dividing data into training and test set
(training_images, training_labels),(test_images, test_labels)=mnist_data.load_data()


Script 46:

In [ ]:
#The images in our dataset are greyscale images, where each
#pixel value lies between 0 and 255. The following script
#normalizes pixel values between 0 and 1.

#scaling images
training_images,test_images=training_images/255, test_images/255

Script 47:

In [ ]:
print(training_images.shape)

Script 48:

In [ ]:
#Let’s print an image randomly from the test set:

#plotting image number 9 from test set
plt.figure()
plt.imshow(test_images[5])
plt.colorbar()
plt.grid(False)
plt.show()

Script 49:

In [ ]:
#converting data into the right shape
training_images=np.expand_dims(training_images,-1)
test_images=np.expand_dims(test_images,-1)
print(training_images.shape)

Script 50:

In [ ]:
#The next step is to find the number of output classes. This
#number will be used to define the number of neurons in the
#output layer.

#printing number of output calsses
output_calsses=len(set(training_labels))
print('Number of output classes is: ',output_calsses)

Script 51:

In [ ]:
training_images[0].shape

Script 52:

In [ ]:
#Developing the CNN model

input_layer = Input(shape = training_images[0].shape)
conv1 = Conv2D(32, (3,3), strides = 2, activation= 'relu')(input_layer)
maxpool1 = MaxPool2D(2, 2)(conv1)
conv2 = Conv2D(64, (3,3), strides = 2, activation= 'relu')(maxpool1)
#conv3 = Conv2D(128, (3,3), strides = 2, activation='relu')(conv2)
flat1 = Flatten()(conv2)
drop1 = Dropout(0.2)(flat1)
dense1 = Dense(512, activation = 'relu')(drop1)
drop2 = Dropout(0.2)(dense1)
output_layer = Dense(output_calsses, activation='softmax')(drop2)

model = Model(input_layer, output_layer)

Script 53:

In [ ]:
#compiling the CNN model
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

Script 54:

In [ ]:
#Finally, execute the following script to print the model architecture.

from tensorflow.keras.utils import plot_model
plot_model(model,to_file='model_plot1.png',show_shapes=True,show_layer_names=True)

Script 55:

In [ ]:
#The following script trains the image classification model.

#training the CNN model
model_history=model.fit(training_images,training_labels,epochs=20,validation_data=(test_images,test_labels),verbose=1)

Script 56:

In [ ]:
#plotting accuracy
import matplotlib.pyplot as plt

plt.plot(model_history.history['accuracy'],label='accuracy')
plt.plot(model_history.history['val_accuracy'],label='val_accuracy')
plt.legend(['train','test'],loc='lower left')

Script 57:

In [ ]:
#making predictions on a single image
output=model.predict(test_images)
prediction=np.argmax(output[5])
print( prediction)

**Exercise 9.1**

**Question 1**

What should be the input shape of the input image to the convolutional neural network?

A. Width, Height

B. Height, Width

C. Channels, Width, Height

**D. Width, Height, Channels**


**Question 2**

We say that a model is overfitting when:

A. Results on test set are better than train set

B. Results on both test and training sets are similar

**C. Results on the training set are better than the results on the test set**

D. None of the above


**Question 3**

The ReLu activation function is used to introduce:

A. Linearity

**B. Non-linearity**

C. Quadraticity

D. None of the above


**Exercise 9.2**

Using the CFAR 10 image dataset, perform image classification to recognize the image. Here is the dataset:
1. cifar_dataset = tf.keras.datasets.cifar10

In [ ]:
#importing required libraries
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input, Conv2D, Dense,Flatten, Dropout, MaxPool2D
from tensorflow.keras.models import Model

cifar_dataset = tf.keras.datasets.cifar10
(training_images, training_labels), (test_images, test_labels) = cifar_dataset.load_data()
training_images, test_images = training_images/255.0,test_images/255.0

training_labels, test_labels = training_labels.flatten(),test_labels.flatten()
print(training_labels.shape)
print(training_images.shape)
output_classes = len(set(training_labels))
print("Number of output classes is: ", output_classes)
input_layer = Input(shape = training_images[0].shape )
conv1 = Conv2D(32, (3,3), strides = 2, activation= 'relu')(input_layer)
maxpool1 = MaxPool2D(2, 2)(conv1)
conv2 = Conv2D(64, (3,3), strides = 2, activation= 'relu')(maxpool1)
#conv3 = Conv2D(128, (3,3), strides = 2, activation='relu')(conv2)
flat1 = Flatten()(conv2)
drop1 = Dropout(0.2)(flat1)
dense1 = Dense(512, activation = 'relu')(drop1)
drop2 = Dropout(0.2)(dense1)
output_layer = Dense(output_classes, activation='softmax')(drop2)

model = Model(input_layer, output_layer)
model.compile(optimizer = 'adam', loss= 'sparse_categorical_crossentropy', metrics =['accuracy'])
model_history = model.fit(training_images, training_labels,epochs=20, validation_data=(test_images, test_labels),verbose=1)

# **10**
# **Dimensionality Reduction with PCA and LDA**
# **Using Sklearn**

**10.1. Principal Component Analysis**

Script 1:

In [ ]:
#imports the required libraries
import pandas as pd
import numpy as np
import seaborn as sns

Script 2:

In [ ]:
#The following script imports the Iris dataset using the Seaborn library and prints the first five rows of the dataset

#importing the dataset
iris_df=sns.load_dataset('iris')

#print dataset head
iris_df.head()

Script 3:

In [ ]:
#The following script divides the data into the features and labels sets

#creating feature set
x=iris_df.drop(['species'],axis=1)

#creating label set
y=iris_df['species']

#converting labels to number
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
y=le.fit_transform(y)

Script 4:

In [ ]:
#Before we apply PCA on a dataset, we will divide it into the training and test sets

#dividing data into 80-20% training and test set
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0 )

Script 5:

In [ ]:
#Finally, both the training and test sets should be scaled before PCA could be applied to them.

#applaying scaling on training and test data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

Script 6: To apply PCA via Sklearn, all you have to do is import the
PCA class from the Sklearn.decomposition module. Next, to
apply PCA to the training set, pass the training set to the fit_
tansform() method of the PCA class object. To apply PCA on the test set, pass the test set to the transform() method of the
PCA class object. This is shown in the following script.

In [ ]:
#importing PCA class
from sklearn.decomposition import PCA

#creating object of the PCA class
pca=PCA()

#training PCA model on training data
x_train=pca.fit_transform(x_train)

#making prediction on test data
x_test=pca.transform(x_test)
from matplotlib import pyplot as plt
%matplotlib inline

#print actual datapoint
plt.scatter(x_test[:,0],x_test[:,1],c=y_test,cmap='rainbow')

Script 7:

In [ ]:
#Once you have applied PCA on a dataset, you can use the
#explained_variance_ratio_ feature to print variance caused by
#all the features in the dataset.

#printing variance ratio
variance_ratios=pca.explained_variance_ratio_
print(variance_ratios)

The output above shows that 72.22 percent of the variance in
the dataset is caused by the first principal component, while
23.97 percent of the variance is caused by the second principal
component.

Let’s now select the two principal components that caused
a collective variance of 96.19 percent (72.22% + 23.97% =
96.19%).

To select two principal components, all you have to do is pass
2 as a value to the n_components attribute of the PCA class.
The following script selects two principal components from
the Iris training and test sets.

Script 8:

In [ ]:
#use one principal component
from sklearn.decomposition import PCA

pca=PCA(n_components=2)
x_train=pca.fit_transform(x_train)
x_test=pca.transform(x_test)



Let’s train a classification model using logistic regression,
which predicts the label of the iris plant using the two principal
components or features, instead of the original four features.

Script 9:

In [ ]:
#making prediction using logistic regression
from sklearn.linear_model import LogisticRegression

#training the logistic regression
lg=LogisticRegression()
lg.fit(x_train,y_train)

#predictin the test set results
y_pred=lg.predict(x_test)

#evaluating results
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))
print(y_test)
print(y_pred)
print(x_test)

The output shows that even with two features, the accuracy
for correctly predicting the label for the iris plant is 86.66.
Finally, with two features, you can easily visualize the dataset
using the following script.

Script 10:

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline

#print actual datapoint
plt.scatter(x_test[:,0],_test[:,1],c=y_test,cmap='rainbow')


**10.2. Linear Discriminant Analysis**

As always, the first step is to import the required libraries.

Script 11:

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns

The following script imports the dataset and displays its first five rows.


Script 12:

In [ ]:
#importing dataset
banknote_df=pd.read_csv('banknote.csv')

#display dataset header
banknote_df.head()

Let’s divide the dataset into features and labels.

Script 13:

In [ ]:
#dividing data into features and labels
x=banknote_df.drop(['class'],axis=1)
y=banknote_df.filter(['class'],axis=1)


Finally, the following script divides the data into training and test sets.

Script 14:

In [ ]:
#dividing data into 80-20% training and test sets
from sklearn.model_selection import trains_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0 )


The data scaling is performed in the following step.

Script 15:

In [ ]:
#applying scaling on training and test data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_test = sc.transform (x_test)

To apply LDA on the test set, pass the test set to
the transform() method of the LDA class object. This is shown in the following script.

Script 16:

In [ ]:
#importing LDA class
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

#creating object of the LDA class
lda = LDA()

#training LDA model on training data
x_train = lda.fit_transform(x_train, y_train)

#making predictions on test data
x_test = lda.transform(x_test)

Like PCA, you can find variance ratios for LDA using the explained_variance_ratio attribute.

Script 17:

In [ ]:
#printing variance ratios
variance_ratios = lda.explained_variance_ratio_
print(variance_ratios)

The above output shows that even with one component, the maximum variance can be achieved.

Next, we select only a single component from our dataset using LDA. To do so, you have to pass 1 as the attribute value for the n_components attribute of the LDA class, as shown below.

Script 18:

In [ ]:
#creating object of the LDA class
lda = LDA(n_components = 1)

#training PCA model on training data
x_train = lda.fit_transform(x_train, y_train)

#making predictions on test data
x_test = lda.transform(x_test)

Next, we will try to class whether or not a banknote is fake using a single feature. We will use the LogisticRegression algorithm for that. This is shown in the following script.

Script 19:

In [ ]:
#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression

#training the logistic regression model
lg = LogisticRegression()
lg.fit(x_train, y_train)

# Predicting the Test set results
y_pred = lg.predict(x_test)

#evaluating results
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, y_pred))

**Exercise 10.1**

**Question 1**

Which of the following are the benefits of dimensionality reduction?

A. Data Visualization

B. Faster training time for statistical algorithms

**C. All of the above**

D. None of the above


**Question 2**

In PCA, dimensionality reduction depends upon the:

**A. Feature set only**

B. Label set only

C. Both features and labels sets

D. None of the above

Question 3

LDA is a __________ dimensionality reduction technique.

A. Unsupervised

B. Semi-Supervised

**C. Supervised**

D. Reinforcement


Exercise 10.2

Apply principal component analysis for dimensionality
reduction on the customer_churn.csv dataset from the Data folder in the book resources. Print the accuracy using the two principal components. Also, plot the results on the test set using the two principal components.

In [ ]:
import pandas as pd
import numpy as np

churn_df = pd.read_csv("customer_churn.csv")
churn_df.head()

In [ ]:
churn_df = churn_df.drop(['RowNumber', 'CustomerId','Surname'], axis=1)
x = churn_df.drop(['Exited'], axis=1)
y = churn_df['Exited']

print('x: ',x.head())
print('y: ',y.head())

In [ ]:
numerical = x.drop(['Geography', 'Gender'], axis = 1)
categorical = x.filter(['Geography', 'Gender'])

cat_numerical = pd.get_dummies(categorical,drop_first=True)
x = pd.concat([numerical, cat_numerical], axis = 1)
x.head()

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.20, random_state=0)

#applying scaling on training and test data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
xtest = sc.transform (x_test)

In [ ]:
#importing PCA class
from sklearn.decomposition import PCA

#creating object of the PCA class
pca = PCA()

#training PCA model on training data
x_train = pca.fit_transform(x_train)

#making predictions on test data
x_test = pca.transform(x_test)

#printing variance ratios
variance_ratios = pca.explained_variance_ratio_
print(variance_ratios)

In [ ]:
#use one principal component
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)

#making predictions using logistic regression
from sklearn.linear_model import LogisticRegression

#training the logistic regression model
lg = LogisticRegression()
lg.fit(x_train, y_train)

# Predicting the Test set results
y_pred = lg.predict(x_test)

#evaluating results
from sklearn.metrics import accuracy_score


print(accuracy_score(y_test, y_pred))

In [ ]:
from matplotlib import pyplot as plt
%matplotlib inline

#print actual datapoints

plt.scatter(x_test[:,0], x_test[:,1], c= y_test, cmap='rainbow' )